config/routes.rb
Rails.application.routes.draw do
  resources :shift_types
  resources :assignments
  resources :rails_nurses
  resources :teams
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get "create_assignment", to: "assignments#new", as: "create_assignment"
  get "auk_download", to: "assignments#download", as: "auk_download"
  get "/solve(/:result)", to: "assignments#solve_index", as: "solve_index"
  post "/solve", to: "assignments#solve", as: "solve"

  get "/blockly", to: "assignments#blockly_index", as: "blockly_index"
  post 'blockly_table', to: 'assignments#blockly_table'
  get 'fetch_schedule_result', to: 'assignments#fetch_schedule_result'

  post '/blocks/run', to: 'blocks#run'

  # Defines the root path route ("/")
  root "assignments#index"
end

app/models/assignment.rb
class Assignment < ApplicationRecord
  belongs_to :rails_nurse
  belongs_to :shift_type, optional: true
  def self.shifts_to_json(range)
    assignments = where(date: range)
    assignments.map do |assignment|
      {
        name: assignment.rails_nurse.name,
        date: assignment.date.strftime("%Y-%m-%d"),
        shift_type: assignment.shift_type.name
      }
    end
  end
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  skip_before_action :verify_authenticity_token # 必要に応じてCSRF保護を設定
  include Sparrow

  #before_action :set_assignment, only: %i[ show edit update destroy ]

  # GET /assignments or /assignments.json
  def index
    today = Date.today

    yyyymm = params[:month].to_s
    yyyy, mm = /(\d{4})(\d{2})/.match(yyyymm).to_a.values_at(1,2).map(&:to_i)

    if Date.valid_date?(yyyy, mm, 1)
      @month = Date.new(yyyy, mm, 1)
    else
      @month = Date.new(today.year, today.month, 1)
    end
    @assignments = Assignment.includes(:shift_type).where(date: @month...(@month >> 1))
    @nurses = RailsNurse.includes(:assignments)

    @shift_names = ShiftType.distinct.pluck(:name)
    @shift_names += ["日勤", "準夜勤", "深夜勤", "休み"] if @shift_names.size < 4

    @shift_types = ShiftType.all
    @nurse_shift_counts = count_shifts_by_nurse
    @daily_shift_counts = count_shifts_by_day
    week_ranges = calculate_week_ranges(@month)
    @weekly_shift_counts = calculate_weekly_shift_counts(week_ranges, @nurses)

    @date_range = @month.to_date...(@month >> 1).to_date
    @total = @shift_types.sum { |shift_type| @nurse_shift_counts.values.sum { |counts| counts[shift_type.name] || 0 } }
  end

  # GET /assignments/1 or /assignments/1.json
  def show
  end

  # GET /assignments/new
  def new
    #@assignment = Assignment.new
    today = Date.today

    yyyymm = params[:month].to_s
    yyyy, mm = /(\d{4})(\d{2})/.match(yyyymm).to_a.values_at(1,2).map(&:to_i)

    if Date.valid_date?(yyyy, mm, 1)
      @month = Date.new(yyyy, mm, 1)
    else
      @month = Date.new(today.year, today.month, 1)
    end
    @nurses = RailsNurse.all
    @desired_date_range = (@month.strftime('%Y%m') + "01").to_date.beginning_of_month..(@month.strftime('%Y%m') + "01").to_date.end_of_month
  end

  # GET /assignments/1/edit
  def edit
  end

  # POST /assignments or /assignments.json
  def create
    today = Date.today

    yyyymm = params[:month].to_s
    yyyy, mm = /(\d{4})(\d{2})/.match(yyyymm).to_a.values_at(1,2).map(&:to_i)

    if Date.valid_date?(yyyy, mm, 1)
      @month = Date.new(yyyy, mm, 1)
    else
      @month = Date.new(today.year, today.month, 1)
    end

    @desired_date_range = (@month.strftime('%Y%m') + "01").to_date.beginning_of_month..(@month.strftime('%Y%m') + "01").to_date.end_of_month

    if params[:nurse_ids].nil?
      redirect_to new_assignment_path(month: @month.strftime("%Y%m")), notice: "シフトに追加したい看護師を選択してください", flash: {color: :red}
    else
      @nurses = RailsNurse.where(id: params[:nurse_ids])
      @nurses.each do |nurse|
        @desired_date_range.each do |date|
          existing_assignment = Assignment.find_by(date: date, rails_nurse_id: nurse.id)
          if existing_assignment.nil?
            # データが存在しない場合は保存
            @assignment = Assignment.new(date: date, rails_nurse_id: nurse.id)
            @assignment.save
          end
        end
      end
      redirect_to assignments_path(month: @month.strftime("%Y%m")), notice: "シフトに看護師が追加されました．", flash: {color: :green}
    end
  end

  # PATCH/PUT /assignments/1 or /assignments/1.json
  def update
    respond_to do |format|
      if @assignment.update(assignment_params)
        format.html { redirect_to assignment_url(@assignment), notice: "割当が更新されました" }
        format.json { render :show, status: :ok, location: @assignment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assignments/1 or /assignments/1.json
  def destroy
    @assignment.destroy

    respond_to do |format|
      format.html { redirect_to assignments_url, notice: "割当が削除されました" }
      format.json { head :no_content }
    end
  end

  def blockly_index

  end

  def blockly_table
    code = params[:code]

    # ジョブIDを生成
    job_id = SecureRandom.uuid

    # 非同期ジョブを実行
    SolveScheduleJob.perform_later(code, job_id)

    # クライアントにジョブIDを返す
    render json: { status: 'job_started', job_id: job_id }
  end

  def fetch_schedule_result
    job_id = params[:job_id]
    Rails.logger.info("Fetching result for job_id: #{job_id}")
    result = Rails.cache.read("schedule_result_#{job_id}")
    Rails.logger.info("Fetched result: #{result}")

    if result
      render json: { status: 'success', html: result }
    else
      render json: { status: 'processing' }
    end
  end

  def create_assignments(json)
    parsed_json = JSON.parse(json)
    shift_hash = parsed_json["shifts"]

    shift_hash.each do |shift_data|
      nurse = RailsNurse.find_by(name: shift_data["name"])

      unless nurse
        team_id = shift_data["team_id"] || 1
        ladder_level = shift_data["ladder_level"] || 1
        nurse = RailsNurse.create!(name: shift_data["name"], team_id: team_id, ladder_level: ladder_level)
      end

      shift = ShiftType.find_by(name: shift_data["shift_type"])

      unless shift
        kind = shift_data["kind"] || 0
        shift = ShiftType.create!(name: shift_data["shift_type"], kind: kind)
      end

      date = shift_data["date"]
      if Assignment.where(date: date, rails_nurse_id: nurse.id).exists?
        Assignment.where(date: date, rails_nurse_id: nurse.id).update_all(shift_type_id: shift.id)
      else
        Assignment.create!(date: date, rails_nurse_id: nurse.id, shift_type_id: shift.id)
      end
    end

    off_shift = ShiftType.find_or_create_by!(name: "休み", kind: 0)

    # 割当のないものを休みにする
    date_range = parsed_json["date_range"]
    range = (Date.parse(date_range["start"])..Date.parse(date_range["end"]))
    range.each do |date|
      assignments = Assignment.where(date: date)
      assignments.each do |assignment|
        if assignment.shift_type_id.nil?
          assignment.update!(shift_type_id: off_shift.id)
        end
      end
    end
  end

  def download
    today = Date.today

    yyyymm = params[:month].to_s
    yyyy, mm = /(\d{4})(\d{2})/.match(yyyymm).to_a.values_at(1,2).map(&:to_i)

    if Date.valid_date?(yyyy, mm, 1)
      @month = Date.new(yyyy, mm, 1)
    else
      @month = Date.new(today.year, today.month, 1)
    end

    shifts = Assignment.includes(:shift_type).where(date: @month...(@month >> 1))
    json = to_json(shifts, @month)
    auk = json_to_auk(json)
    write_auk(auk)
    file_path = Rails.root.join("public", "AUK", "example.auk")
    send_file(file_path, filename: "generated_file.auk", type: "text/plain")
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_assignment
      @assignment = Assignment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def assignment_params
      params.require(:assignment).permit(:date, :nurse_id, :shift_type_id, :state)
    end

    def count_shifts_by_shift_type(shift_type)
      shift_type.assignments.where(date: @month...(@month >> 1)).count
    end

    def count_shifts_by_nurse
      nurse_shift_counts = {}
      @assignments.group_by(&:rails_nurse_id).each do |nurse_id, nurse_assignments|
        shift_counts = {}
        @shift_types.each do |shift_type|
          shift_counts[shift_type.name] = nurse_assignments.count { |a| a.shift_type_id == shift_type.id }
        end
        nurse_shift_counts[nurse_id] = shift_counts
      end
      nurse_shift_counts
    end

    private

    def calculate_week_ranges(month)
      start_date = month.beginning_of_month
      start_date -= start_date.wday - 1 if start_date.wday != 1 # 月曜日始まりに調整
      start_date = start_date.beginning_of_week(:monday) unless month.beginning_of_month.wday == 1
      end_date = month.end_of_month
      week_ranges = []
      current_start_date = start_date
      while current_start_date <= end_date
        current_end_date = current_start_date + 6.days
        week_ranges << (current_start_date..current_end_date)
        current_start_date = current_end_date + 1.day
      end
      week_ranges
    end

    def calculate_weekly_shift_counts(week_ranges, nurses)
      week_ranges.map do |week_dates|
        {
          week_dates: week_dates,
          nurse_shift_counts: nurses.each_with_object({}) do |nurse, counts|
            nurse_assignments = nurse.assignments || []
            week_range = week_dates.first..week_dates.last
            # 該当週のシフトデータを集計
            counts[nurse.id] = nurse_assignments
              .select { |a| week_range.cover?(a.date) }
              .group_by { |a| a.shift_type&.name }
              .transform_values(&:count)
          end
        }
      end
    end

    def count_shifts_by_day
      daily_shift_counts = {}
      (@month...(@month >> 1)).each do |day|
        daily_shifts = @assignments.where(date: day)
        shift_counts = {}
        @shift_types.each do |shift_type|
          shift_counts[shift_type.name] = daily_shifts.where(shift_type_id: shift_type.id).count
        end
        daily_shift_counts[day] = shift_counts
      end
      daily_shift_counts
    end

    def create_assignments(json)
      shift_hash = JSON.parse(json)["shifts"]
      shift_hash.each do |shift|
        nurse = RailsNurse.find_by(name: shift["name"])
        date = shift["date"]
        shift = ShiftType.find_by(name: shift["shift_type"])
        if Assignment.where(date: date, rails_nurse_id: nurse.id).exists?
          Assignment.where(date: date, rails_nurse_id: nurse.id).update(shift_type_id: shift.id)
        else
          Assignment.create(date: date, rails_nurse_id: nurse.id, shift_type_id: shift.id)
        end
      end
      off_shift = ShiftType.find_by(name: "休み")
      # 割当のないものを休みに
      date_range = JSON.parse(json)["date_range"]
      range = (Date.parse(date_range["start"])..Date.parse(date_range["end"]))
      range.each do |date|
        assignments = Assignment.where(date: date)
        assignments.each do |assignment|
          if assignment.shift_type_id.nil?

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/views/assignments/_assignment.html.erb
<div id="<%= dom_id assignment %>">
  <p>
    <strong>Date:</strong>
    <%= assignment.date %>
  </p>

  <p>
    <strong>Rails nurse:</strong>
    <%= assignment.rails_nurse_id %>
  </p>

  <p>
    <strong>Shift type:</strong>
    <%= assignment.shift_type_id %>
  </p>

  <p>
    <strong>State:</strong>
    <%= assignment.state %>
  </p>

</div>

app/views/assignments/_form.html.erb
<%= form_with(model: assignment) do |form| %>
  <% if assignment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(assignment.errors.count, "error") %> prohibited this assignment from being saved:</h2>

      <ul>
        <% assignment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :date, style: "display: block" %>
    <%= form.date_field :date %>
  </div>

  <div>
    <%= form.label :rails_nurse_id, style: "display: block" %>
    <%= form.text_field :rails_nurse_id %>
  </div>

  <div>
    <%= form.label :shift_type_id, style: "display: block" %>
    <%= form.text_field :shift_type_id %>
  </div>

  <div>
    <%= form.label :state, style: "display: block" %>
    <%= form.number_field :state %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/assignments/edit.html.erb
<h1>Editing assignment</h1>

<%= render "form", assignment: @assignment %>

<br>

<div>
  <%= link_to "Show this assignment", @assignment %> |
  <%= link_to "Back to assignments", assignments_path %>
</div>

app/views/assignments/new.html.erb
<% if flash[:color] == "red" %>
  <div class="red-text"><%= flash[:notice] %></div>
<% elsif flash[:color] == "green" %>
  <div class="green-text"><%= flash[:notice] %></div>
<% else %>
  <div><%= flash[:notice] %></div>
<% end %>

<div class="row">
  <div class="col-lg-4 col-md-12"><h2><%= "#{@month.strftime("%Y年%m月")}のシフトを作成" %></h2></div>
  <div class="col-lg-6 col-md-0"></div>
  <div class="col-lg-2 col-md-12"><%= link_to "#{@month.strftime("%Y")}年#{@month.strftime("%m")}月のシフトへ戻る", assignments_path(month: @month.strftime("%Y%m")), class: "btn btn-outline-primary" %></div>
</div>

<%= form_tag assignments_path(month: @month.strftime("%Y%m")), method: :post do %>
<div class="row mb-3">
  <div class="col-lg-1 col-md-0"></div>
  <div class="col-lg-10 col-md-12">
    <div class="card">
      <div class="card-header">
          <div class="row">
            <div class="col-3 d-flex align-items-center">看護師のシフト登録</div>
            <div class="col-6"></div>
            <div class="col-3"><%= submit_tag "選択した看護師をシフトに追加", class: "ms-5 btn btn-success px-3" %></div>
          </div>
      </div>
      <div class="card-body m-3">
        <div class="row border-bottom border-dark pb-3">
          <div class="col my-auto fw-bolder h5">看護師選択</div>
          <div class="col my-auto fw-bolder h5">看護師名</div>
          <div class="col my-auto fw-bolder h5">ラダーレベル</div>
          <div class="col my-auto fw-bolder h5">チーム</div>
        </div>
      <div>
        <% @nurses.each do |nurse| %>
          <div class="row border-bottom px-3 py-2">
            <% if Assignment.where(date: @desired_date_range, rails_nurse_id: nurse.id).count >= 1 %>
              <div class="col my-auto"><%= "勤務表に登録済み" %></div>
            <% else %>
              <div class="col my-auto"><%= check_box_tag "nurse_ids[]", nurse.id %></div>
            <% end %>
            <div class="col my-auto"><%= nurse.name %></div>
            <div class="col my-auto"><%= nurse.ladder_level %></div>
            <div class="col my-auto"><%= nurse.team.name %></div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/assignments/show.html.erb
<% if flash[:color] == "red" %>
  <div class="red-text"><%= flash[:notice] %></div>
<% elsif flash[:color] == "green" %>
  <div class="green-text"><%= flash[:notice] %></div>
<% else %>
  <div><%= flash[:notice] %></div>
<% end %>

<%= render @assignment %>

<div>
  <%= link_to "Edit this assignment", edit_assignment_path(@assignment) %> |
  <%= link_to "Back to assignments", assignments_path %>

  <%= button_to "Destroy this assignment", @assignment, method: :delete %>
</div>

app/views/assignments/solve_index.html.erb
<h1>スケジュール生成</h1>

<%= form_with url: solve_path do |form| %>
  <%= form.file_field :file %>
  <%= form.submit "入力" %>
<% end %>

<%= raw @html %>