config/routes.rb
Rails.application.routes.draw do
  resources :shift_types
  resources :assignments
  resources :rails_nurses
  resources :teams
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get "create_assignment", to: "assignments#new", as: "create_assignment"
  get "auk_download", to: "assignments#download", as: "auk_download"
  get "/solve(/:result)", to: "assignments#solve_index", as: "solve_index"
  post "/solve", to: "assignments#solve", as: "solve"

  get "/blockly", to: "assignments#blockly_index", as: "blockly_index"
  post 'blockly_table', to: 'assignments#blockly_table'
  get 'fetch_schedule_result', to: 'assignments#fetch_schedule_result'

  post '/blocks/run', to: 'blocks#run'

  # Defines the root path route ("/")
  root "assignments#index"
end

app/controllers/nurses_controller.rb
class NursesController < ApplicationController
  before_action :set_nurse, only: %i[ show edit update destroy ]

  # GET /nurses or /nurses.json
  def index
    @q = Nurse.ransack(params[:q])
    @nurses = @q.result(distinct: true)
  
    if @nurses.blank?
      @nurses = Nurse.all
    end
  end 

  # GET /nurses/1 or /nurses/1.json
  def show
    today = Date.today

    yyyymm = params[:month].to_s
    yyyy, mm = /(\d{4})(\d{2})/.match(yyyymm).to_a.values_at(1,2).map(&:to_i)

    if Date.valid_date?(yyyy, mm, 1)
      @month = Date.new(yyyy, mm, 1)
    else
      @month = Date.new(today.year, today.month, 1)
    end
    @assignments = Assignment.where(nurse_id: @nurse.id, date: @month...(@month >> 1))
    @shift_types = ShiftType.all
    @shift_type_counts = {}
    @total = 0
    @shift_types.each do |shift_type|
      @shift_type_counts[shift_type.name] = count_shifts_by_shift_type(shift_type)
      @total += @shift_type_counts[shift_type.name]
    end
  end

  # GET /nurses/new
  def new
    @nurse = Nurse.new
    @teams = Team.distinct.joins(:nurses).select(:id, :name)
  end

  # GET /nurses/1/edit
  def edit
    @teams = Team.distinct.joins(:nurses).select(:id, :name)
  end

  # POST /nurses or /nurses.json
  def create
    @nurse = Nurse.new(nurse_params)

    respond_to do |format|
      if @nurse.save
        format.html { redirect_to nurse_url(@nurse), notice: "看護師が登録されました" }
        format.json { render :show, status: :created, location: @nurse }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @nurse.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nurses/1 or /nurses/1.json
  def update
    respond_to do |format|
      if @nurse.update(nurse_params)
        format.html { redirect_to nurse_url(@nurse), notice: "看護師情報が更新されました" }
        format.json { render :show, status: :ok, location: @nurse }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @nurse.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nurses/1 or /nurses/1.json
  def destroy
    @nurse.destroy

    respond_to do |format|
      format.html { redirect_to nurses_url, notice: "看護師が削除されました" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_nurse
      @nurse = Nurse.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def nurse_params
      params.require(:nurse).permit(:name, :ladder_level, :team_id)
    end

    def count_shifts_by_shift_type(shift_type)
      @assignments.where(shift_type_id: shift_type.id).count
    end
end

app/views/nurses/_nurse.html.erb
<div id="<%= dom_id nurse %>">
  <p>
    <strong>Name:</strong>
    <%= nurse.name %>
  </p>

  <p>
    <strong>Ladder level:</strong>
    <%= nurse.ladder_level %>
  </p>

  <p>
    <strong>Team:</strong>
    <%= nurse.team_id %>
  </p>

</div>

app/views/nurses/edit.html.erb
<div class="row">
  <div class="col-lg-4 col-md-12"><h2>編集(<%= @nurse.name %>)</h2></div>
  <div class="col-lg-6 col-md-0"></div>
  <div class="col-lg-2 col-md-12"><%= link_to "看護師一覧へ", nurses_path, class: "btn btn-outline-primary" %></div>
</div>

<%= render "form", nurse: @nurse %>

app/views/nurses/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="row">
  <div class="col-lg-4 col-md-12"><h2>看護師一覧</h2></div>
  <div class="col-lg-6 col-md-0"></div>
  <div class="col-lg-2 col-md-12"><%= link_to "新規登録", new_nurse_path, class: "btn btn-outline-primary" %></div>
</div>

<%= search_form_for @q, url: nurses_path, method: :get do |f| %>
  <div class="form-group">
    <%= f.label :name_cont, "氏名" %>
    <%= f.search_field :name_cont, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :team_name_cont, "チーム" %>
    <%= f.search_field :team_name_cont, class: "form-control" %>
  </div>
  <%= f.submit "検索", class: "btn btn-primary" %>
  <%= link_to "クリア", nurses_path, class: "btn btn-danger" %>
<% end %>

<table class="table">
  <thead>
    <tr>
      <th><%= sort_link(@q, :name, "氏名") %></th>
      <th><%= sort_link(@q, :team_name, "チーム") %></th>
      <th><%= sort_link(@q, :ladder_level, "ラダーレベル") %></th>
      <th><%= "操作" %></th>
    </tr>
  </thead>
  <tbody>
    <% @nurses.each do |nurse| %>
      <tr>
        <td><%= link_to_if nurse.name, nurse.name, nurse %></td>
        <td><%= link_to_if nurse.team.name, nurse.team.name, nurse.team %></td>
        <td><%= nurse.ladder_level %></td>
        <td>
          <div class="d-flex">
            <%= link_to "詳細", nurse_path(nurse), class: "btn btn-primary" %>
            <%= link_to "編集", edit_nurse_path(nurse), class: "btn btn-success" %>
            <% if nurse.assignments == nil %>
              <%= button_to "削除", nurse, method: :delete, class: "btn btn-danger" %>
            <% end %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/nurses/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="row">
  <div class="col-lg-4 col-md-12"><h2><%= @nurse.name %>のページ</h2></div>
  <div class="col-lg-6 col-md-0"></div>
  <div class="col-lg-2 col-md-12"><%= link_to "看護師一覧へ", nurses_path, class: "btn btn-outline-primary" %></div>
</div>

<div class="row my-3">
<div class="col-lg-3 col-md-6 d-flex align-items-center h5">ラダーレベル: <%= @nurse.ladder_level %></div>
<div class="col-lg-3 col-md-6 d-flex align-items-center h5">チーム: <%= @nurse.team_id %></div>
</div>

<%= link_to "←", nurse_path(@nurse.id, month: (@month <<1).strftime("%Y%m")) %>
<%= link_to "→", nurse_path(@nurse.id, month: (@month >>1).strftime("%Y%m")) %>

<div id="assignments">
  <% assignment_table = {} %>
  <% @assignments.each do |assignment| %>
    <% date = assignment.date %>
    <% nurse = assignment.nurse %>
    <% name = assignment.shift_type.name %>
    <% name_abbrev = name[0] %>
    <% unless assignment_table[nurse.id] %>
      <% assignment_table[nurse.id] = {} %>
    <% end %>
    <% assignment_table[nurse.id][date] = name_abbrev %>
  <% end %>

  <table border="1">
    <th>
      <% (@month...(@month >> 1)).each do |date| %>
        <td><%= date.strftime("%d") %></td>
      <% end %>
      <td><%= "日" %></td>
      <td><%= "準" %></td>
      <td><%= "深" %></td>
      <td><%= "休" %></td>
    </th>
    <% assignment_table[@nurse.id] ||= {} %>
    <tr>
    <td><%= link_to_if @nurse.name, @nurse.name, @nurse %></td>
      <% (@month...(@month >> 1)).each do |date| %>
        <% shift_name = assignment_table[@nurse.id][date] || "休" %>
        <td><%= shift_name %></td>
      <% end %>
    <td class="right-align"><%= @shift_type_counts["日勤"] %></td>
    <td class="right-align"><%= @shift_type_counts["準夜勤"] %></td>
    <td class="right-align"><%= @shift_type_counts["深夜勤"] %></td>
    <td class="right-align"><%= ((@month >> 1) - @month).to_i  - @total %></td>
    </tr>
  </table>
</div>