config/routes.rb
Rails.application.routes.draw do
  resources :shift_types
  resources :assignments
  resources :rails_nurses
  resources :teams
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get "create_assignment", to: "assignments#new", as: "create_assignment"
  get "auk_download", to: "assignments#download", as: "auk_download"
  get "/solve(/:result)", to: "assignments#solve_index", as: "solve_index"
  post "/solve", to: "assignments#solve", as: "solve"

  get "/blockly", to: "assignments#blockly_index", as: "blockly_index"
  post 'blockly_table', to: 'assignments#blockly_table'
  get 'fetch_schedule_result', to: 'assignments#fetch_schedule_result'

  post '/blocks/run', to: 'blocks#run'

  # Defines the root path route ("/")
  root "assignments#index"
end

app/controllers/shift_types_controller.rb
class ShiftTypesController < ApplicationController
  before_action :set_shift_type, only: %i[ show edit update destroy ]

  # GET /shift_types or /shift_types.json
  def index
    @shift_types = ShiftType.all
  end

  # GET /shift_types/1 or /shift_types/1.json
  def show
  end

  # GET /shift_types/new
  def new
    @shift_type = ShiftType.new
  end

  # GET /shift_types/1/edit
  def edit
  end

  # POST /shift_types or /shift_types.json
  def create
    @shift_type = ShiftType.new(shift_type_params)

    respond_to do |format|
      if @shift_type.save
        format.html { redirect_to shift_type_url(@shift_type), notice: "Shift type was successfully created." }
        format.json { render :show, status: :created, location: @shift_type }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @shift_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shift_types/1 or /shift_types/1.json
  def update
    respond_to do |format|
      if @shift_type.update(shift_type_params)
        format.html { redirect_to shift_type_url(@shift_type), notice: "Shift type was successfully updated." }
        format.json { render :show, status: :ok, location: @shift_type }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @shift_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shift_types/1 or /shift_types/1.json
  def destroy
    @shift_type.destroy

    respond_to do |format|
      format.html { redirect_to shift_types_url, notice: "Shift type was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shift_type
      @shift_type = ShiftType.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def shift_type_params
      params.require(:shift_type).permit(:name, :kind)
    end
end

app/helpers/shift_types_helper.rb
module ShiftTypesHelper
end

app/views/shift_types/_form.html.erb
<%= form_with(model: shift_type) do |form| %>
  <% if shift_type.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(shift_type.errors.count, "error") %> prohibited this shift_type from being saved:</h2>

      <ul>
        <% shift_type.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :kind, style: "display: block" %>
    <%= form.number_field :kind %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/shift_types/_shift_type.html.erb
<div id="<%= dom_id shift_type %>">
  <p>
    <strong>Name:</strong>
    <%= shift_type.name %>
  </p>

  <p>
    <strong>Kind:</strong>
    <%= shift_type.kind %>
  </p>

</div>

app/views/shift_types/edit.html.erb
<h1>Editing shift type</h1>

<%= render "form", shift_type: @shift_type %>

<br>

<div>
  <%= link_to "Show this shift type", @shift_type %> |
  <%= link_to "Back to shift types", shift_types_path %>
</div>

app/views/shift_types/index.html.erb
<% if flash[:color] == "red" %>
  <div class="red-text"><%= flash[:notice] %></div>
<% elsif flash[:color] == "green" %>
  <div class="green-text"><%= flash[:notice] %></div>
<% else %>
  <div><%= flash[:notice] %></div>
<% end %>

<h1>Shift types</h1>

<div id="shift_types">
  <% @shift_types.each do |shift_type| %>
    <%= render shift_type %>
    <p>
      <%= link_to "Show this shift type", shift_type %>
    </p>
  <% end %>
</div>

<%= link_to "New shift type", new_shift_type_path %>

app/views/shift_types/new.html.erb
<h1>New shift type</h1>

<%= render "form", shift_type: @shift_type %>

<br>

<div>
  <%= link_to "Back to shift types", shift_types_path %>
</div>

app/views/shift_types/show.html.erb
<% if flash[:color] == "red" %>
  <div class="red-text"><%= flash[:notice] %></div>
<% elsif flash[:color] == "green" %>
  <div class="green-text"><%= flash[:notice] %></div>
<% else %>
  <div><%= flash[:notice] %></div>
<% end %>

<%= render @shift_type %>

<div>
  <%= link_to "Edit this shift type", edit_shift_type_path(@shift_type) %> |
  <%= link_to "Back to shift types", shift_types_path %>

  <%= button_to "Destroy this shift type", @shift_type, method: :delete %>
</div>