config/routes.rb
Rails.application.routes.draw do
  resources :shift_types
  resources :assignments
  resources :rails_nurses
  resources :teams
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get "create_assignment", to: "assignments#new", as: "create_assignment"
  get "auk_download", to: "assignments#download", as: "auk_download"
  get "/solve(/:result)", to: "assignments#solve_index", as: "solve_index"
  post "/solve", to: "assignments#solve", as: "solve"

  get "/blockly", to: "assignments#blockly_index", as: "blockly_index"
  post 'blockly_table', to: 'assignments#blockly_table'
  get 'fetch_schedule_result', to: 'assignments#fetch_schedule_result'

  post '/blocks/run', to: 'blocks#run'

  # Defines the root path route ("/")
  root "assignments#index"
end

app/views/layouts/_header.html.erb
<nav class="navbar sticky-top navbar-expand-sm navbar-light bg-info mb-3 z-50">
  <div>
    <%= link_to "modernTimes", assignments_path, method: :get, class: "navbar-brand" %>
  </div>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li><%= link_to "看護師一覧", rails_nurses_path, method: :get, class: "nav-link" %></li>
      <li><%= link_to "シフト", assignments_path, method: :get, class: "nav-link" %></li>
      <li><%= link_to "チーム一覧", teams_path, method: :get, class: "nav-link" %></li>
      <li><%= link_to "シフト作成", blockly_index_path, method: :get, class: "nav-link" %></li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ModernTimes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "custom_styles", media: "all", "data-turbolinks-track": "reload" %>
    <%= stylesheet_link_tag "blockly_custom", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "blockly", "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <%= render partial: "layouts/header" %>
    <%= yield %>
  </body>
</html>